services:
  web-server-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: europe-west2-docker.pkg.dev/signalling-api/voneo/voneo-frontend:1.0.0
    ports:
      - "8080:8080"

  web-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: web-server-dev:1.0.0
    ports:
      - "4321:4321"
    develop:
      watch:
        - action: sync
          path: .
          target: /app