# syntax=docker/dockerfile:1

FROM dhi.io/node:26-alpine-dev AS dev

WORKDIR /app

COPY package.json package-lock.json* .

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD ["node","app.js"]

